"""Roles can be nullable

Revision ID: a40336eb3dc5
Revises: ae144d1f417c
Create Date: 2025-10-01 19:39:31.809965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a40336eb3dc5'
down_revision = 'ae144d1f417c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'role',
               existing_type=postgresql.ENUM('DEVELOPER', 'TESTER', 'ADMINISTRATOR', name='roles'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'role',
               existing_type=postgresql.ENUM('DEVELOPER', 'TESTER', 'ADMINISTRATOR', name='roles'),
               nullable=False)
    # ### end Alembic commands ###
